version: "3.9"

services:
  proton-bank-fe:
    build: .
    container_name: proton-banking-fe
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - ai_agent_network
    restart: unless-stopped

networks:
  ai_agent_network:
    external: true

